# Generated by Django 4.2.6 on 2023-10-09 21:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display', models.CharField(max_length=255)),
                ('fields', jsonfield.fields.JSONField(null=True)),
                ('keys', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_list', to='core.product')),
            ],
        ),
    ]
